feat/add flights api
ccrsxx/plane-ticket-be pull request #26
Opened 2024-11-28 02:57 UTC by niemoo

Add two new API endpoints for managing flight-related data:
- /flights
- /flights/favorites

2024-11-28 05:25 UTC, ccrsxx commented on src/services/flight.js
> +) {
better pake lgsg query object aja dari zod schema yg udh dibuat, karena udh divalidasi tinggal pake type-nya.

```js
/** @import {ValidFlightPayload, ValidFavoriteFlightPayload} from '../middlewares/validation/flight.js' */

/**
 * @param {ValidFlightPayload}  query
 */
async function getFlights(query / lgsg spread { departureAirportId, ...etc }) {
}
```

kode atas rada unsafe misal, salah masukin order parameternya. plus convert datenya di service-nya aja jadinya gk di controller.

2024-11-28 05:26 UTC, ccrsxx commented on src/services/flight.js
> +async function getFavoriteFlights(continent) {
Pake cara yg diatas juga biar ke ambil otomatis type-nya.

2024-11-28 05:30 UTC, ccrsxx commented on src/middlewares/validation/flight.js
> +function isValidFlightPayload(req, _res, next) {
NIT: better pake valid name function `isValidFlightQueryParams`, Karena payload itu kan kita verify body, sama kek functionnya bawah yg buat favorite.

2024-11-28 05:31 UTC, ccrsxx requested changes
Overall udh ok, cuman beberapa kode dibenerin biar lebih clear dan tambah safe.

2024-11-28 07:53 UTC, niemoo commented on src/services/flight.js
> +) {
done

2024-11-28 07:53 UTC, niemoo commented on src/services/flight.js
> +async function getFavoriteFlights(continent) {
done

2024-11-28 14:26 UTC, ccrsxx reviewed
LGTM but waiting for testing on seeder data.

2024-12-02 13:13 UTC, ccrsxx approved these changes
LGTM!

2024-12-02 13:14 UTC, merged