feat: add notifications endpoint
ccrsxx/plane-ticket-be pull request #37
Opened 2024-12-03 14:18 UTC by alifaaziz

create notifications endpoint #31 :
- get all notifications by userId from token
- read all notifications
- read a notification
- delete notification

2024-12-04 08:47 UTC, ccrsxx commented
@alifaaziz jangan lupa buat postman requestnya, biar testnya entar gampang.

2024-12-05 10:25 UTC, alifaaziz commented
> @alifaaziz jangan lupa buat postman requestnya, biar testnya entar gampang.

done bang

2024-12-05 14:41 UTC, ccrsxx commented on src/controllers/notification.js
> +  const notifications = await NotificationService.getNotifications(userId);
nit: lgsg aja res.local.user.id di parameternya, lebih clean, jangan buat variable baru

2024-12-05 14:41 UTC, ccrsxx commented on src/controllers/notification.js
> +  await NotificationService.readAllNotifications(userId);
nit: lgsg aja res.local.user.id di parameternya, lebih clean, jangan buat variable baru

2024-12-05 14:44 UTC, ccrsxx commented on src/controllers/notification.js
> +  res.status(200).json({ message: 'All notifications marked as read' });
grammar better ganti ke "All notifications have been marked as read"

2024-12-05 14:44 UTC, ccrsxx commented on src/controllers/notification.js
> +  res.status(200).json({ message: `Notification ${id} marked as read` });
ganti ke 'Notification has been marked as read', gk usah mention id

2024-12-05 14:44 UTC, ccrsxx commented on src/controllers/notification.js
> +  res.status(200).json({ message: `Notification ${id} deleted` });
ganti ke  'Notification has been deleted'

2024-12-05 14:45 UTC, ccrsxx commented on src/controllers/notification.js
> +  await NotificationService.deleteNotification(id, userId);
lgsg ke pake param, tanpa buat variable baru

2024-12-05 14:45 UTC, ccrsxx commented on src/routes/notifications.js
> +    '/:id',
pake commonValidationUuid sebelum is authorized

2024-12-05 14:45 UTC, ccrsxx commented on src/routes/notifications.js
> +    AuthMiddleware.isAuthorized,
pake commonValidationUuid sebelum is authorized

2024-12-05 14:48 UTC, ccrsxx commented on src/services/notification.js
> +  }
ini bisa di buat middleware abis isAuthorized, namanya isNotificationExists. jadi bisa reusable di dua routes.
jadi bisa remove check notif gk diatas, jadi pure lewat middleware.

buat middleware-nya di /middlewares/notification.js.

2024-12-05 14:49 UTC, ccrsxx approved these changes
Overall good, tapi perlu improvement lagi.

2024-12-05 14:50 UTC, ccrsxx requested changes
Overall good, tapi perlu improvement lagi.

2024-12-05 15:44 UTC, ccrsxx commented
![image](https://github.com/user-attachments/assets/ce7f4294-28b3-4590-958e-df534c4d43c3)

btw bad response yg 400 sama 404 belum ada.

2024-12-08 09:21 UTC, niemoo approved these changes
LGTM

2024-12-09 13:16 UTC, ccrsxx approved these changes
OK

2024-12-09 13:17 UTC, merged