feat: add update user
ccrsxx/plane-ticket-be pull request #39
Opened 2024-12-05 14:37 UTC by dindalolyta23

2024-12-05 15:15 UTC, niemoo reviewed
nextnya package-lock.json dan package.json jangan diganti-ganti.

2024-12-05 15:28 UTC, niemoo requested changes

2024-12-05 15:28 UTC, niemoo commented on src/services/user.js
> +/**
bisa pakai zod validation type

2024-12-05 15:30 UTC, niemoo commented on src/services/user.js
> + */
bisa disederhanakan pakai zod validation type

2024-12-05 15:32 UTC, niemoo requested changes

2024-12-05 15:32 UTC, niemoo commented on package.json
> +    "plane-ticket-be": "file:",
sama seperti pr sebelumnya, ada anomali di package-lock.json dan package.json

2024-12-10 15:02 UTC, ccrsxx commented
Already implemented on 1c9a6011f9c75880aed83fb88f601c0948b4c691

2024-12-10 15:02 UTC, closed without merging